version: '3.8'

services:
  app:
    build:
      context: .
    init: true
    environment:
      - VIRTUAL_HOST=graph-js.vox.here
    expose:
      - '3000'
    networks:
      - default
      - nginx-proxy
    extra_hosts:
      - 'graph-js.vox.here:127.0.0.1'
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
        volume:
          nocopy: true
      - type: volume
        source: yarn_cache
        target: /var/cache/yarn
    secrets:
      - environment
  neo4j:
    image: neo4j/neo4j-arm64-experimental:4.4.0
    environment:
      - "NEO4J_AUTH=none"
      - "NEO4J_dbms_default__listen__address=0.0.0.0"
      - "NEO4J_dbms_directories_plugins=labs"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4JLABS_PLUGINS='[\"apoc\"]'"
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
    expose:
      - '7474'
    ports:
      - '7474:7474'
      - '7687:7687'

volumes:
  neo4j_data:
  node_modules:
  yarn_cache:

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy

secrets:
  environment:
    file: .env
